### ISSUE TITLE
Create React App build fails

### ISSUE THREAD

**Issue by chrisurlaub** [mosch/react-avatar-editor#229] opened 2018-03-09 15:37 UTC
When I'm building with CRA it fails with:

`Failed to compile.
Failed to minify the code from this file: 

 	./node_modules/react-avatar-editor/dist/index.js:36 

Read more here: http://bit.ly/2tRViJ9
`

Seems it's not happy with async/await.

**Comment by mosch** [comment] 2018-03-09 17:38
Hey @chrisurlaub , which version did you  try?

**Comment by chrisurlaub** [comment] 2018-03-09 18:01
Hi! It was 11.0.0

**Comment by mosch** [comment] 2018-03-09 18:41
I'll investigate . Thanks for reporting.

**Comment by mosch** [comment] 2018-03-12 07:24
Could not reproduce. Can you create a repository that shows this?

**Comment by chrisurlaub** [comment] 2018-03-12 10:57
Hi! I create an empty folder, cd into it, then 

```
create-react-app avatar-test
cd avatar-test/
yarn add react-avatar-editor
vi src/App.js
```

Edit App.js so it looks like:
```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import AvatarEditor from 'react-avatar-editor'

class App extends Component {
  render() {
    return (
```

Then run the build cmd:
```
yarn build

yarn build v0.21.3
$ react-scripts build 
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

        ./node_modules/react-avatar-editor/dist/index.js:36 

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
```

the package.json:
```
{
  "name": "avatar-test",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.2.0",
    "react-avatar-editor": "^11.0.0",
    "react-dom": "^16.2.0",
    "react-scripts": "1.1.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

My NodeJs-version is 9.8.0

**Comment by Leonya** [comment] 2018-03-12 16:58
I can confirm 11.0 no longer works for me, seemingly because you've removed Uglify from the build. `dist/index.js` is now ES2015 code, not ES5, so if you try to use it on a project without Babel, Uglify fails with `Unexpected token: keyword (function)` when an `async` function is encountered.

**Comment by mosch** [comment] 2018-03-12 19:24
@chrisurlaub @Leonya should be fixed in 11.0.1, could you verify?

**Comment by chrisurlaub** [comment] 2018-03-13 09:07
Hi! Thanks a lot for the fix though it introduced a new error.

The build works now but in my browsers (Chrome, Firefox) I get 

```
ReferenceError: regeneratorRuntime is not defined
(anonymous function)
node_modules/react-avatar-editor/dist/index.js:1
```

I think this is related babel / babel-polyfill

**Comment by dan-lee** [comment] 2018-03-13 09:09
@chrisurlaub Yeah, you're right `babel-polyfill` is now required on userland, which it shouldn't of course. I'll take a look at this.

**Comment by dan-lee** [comment] 2018-03-13 13:54
@chrisurlaub @Leonya @menelike Just published a patch version, can you check if it works for you? Thanks

**Comment by Leonya** [comment] 2018-03-13 14:01
Thanks, works fine now.

**Comment by chrisurlaub** [comment] 2018-03-13 14:08
Same here, it works! Thanks a lot!

**Comment by dan-lee** [comment] 2018-03-13 14:24
Alright, thank you all and apologies 😇

**Closed by dan-lee** 2018-03-13 14:24 UTC

**Comment by mosch** [comment] 2018-03-13 14:27
🎊 thank you for working it out!
