### ISSUE TITLE
Read property is undefined in mobile devices

### ISSUE THREAD

**Issue by dimanchee** [mosch/react-avatar-editor#20] opened 2015-03-11 09:43 UTC
I am integrating this plugin in mobile devices, while I am touching the image I got this error message in console log:

- Uncaught TypeError: Cannot read property '0' of undefined, this reference to this code in the plugin 
var mousePositionX = TOUCH ? event.targetTouches[0].pageX : e.clientX;

- Uncaught TypeError: Cannot read property 'files' of undefined, refer to 
reader.readAsDataURL(e.dataTransfer.files[0]);

Calling plugin: 

return (
<AvatarEditor ref="editor" image="http://upload.wikimedia.org/wikipedia/commons/f/f8/Ellen_H._Swallow_Richards_House_Boston_MA_01.jpg" width={250} height={205} border={50} scale={1.2} />;
);

Anything wrong?

**Comment by dimanchee** [comment] 2015-03-11 10:53
I just realize that, there is no problem viewing in browsers. But It is not working in devices. Does this plugin support touch event in mobile devices?

**Comment by mosch** [comment] 2015-03-14 19:27
Touch Events were added [here](https://github.com/mosch/react-avatar-editor/pull/14). It looks like it was not tested well. Can you look into this?

**Comment by dimanchee** [comment] 2015-03-16 02:29
@mosch 
Suggest to update little patch below on Line 97 to enable touch event in devices:

var eventMove = navigator.userAgent.match(/(Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini)/) ? 'touchmove' : 'mousemove';
            document.addEventListener(eventMove, this.handleMouseMove, false);

**Comment by mosch** [comment] 2015-05-20 08:35
@dimanchee this need some more work to do. I would love if you digg deeper into this!

**Comment by mosch** [comment] 2015-06-17 12:56
Cannot reproduce anymore, so closing this. Feel free to shout if this is still wrong.

**Closed by mosch** 2015-06-17 12:56 UTC
