### ISSUE TITLE
Could not find a declaration file for module 'react-avatar-editor'. 'C:/.../node_modules/react-avatar-editor/dist/index.js' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by azaelvaldo** [mosch/react-avatar-editor#410] opened 2023-12-29 16:56 UTC
Any suggestions? my company eslint have a strong policies.

**Comment by rexwangcc** [comment] 2024-01-14 13:18
Seems like a duplicate of https://github.com/mosch/react-avatar-editor/issues/393? Basically you can try either of the following:

```shell
# npm i @types/react-avatar-editor
yarn add @types/react-avatar-editor
```

**Comment by mosch** [comment] 2024-01-14 18:22
Upgrade to the latest version. It comes with types.

**Closed by mosch** 2024-01-14 18:22 UTC
